version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    container_name: "pgdb"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/musicgenius
    ports:
      - "8000:8000"
    depends_on:
      - db