# Generated by Django 2.2.7 on 2019-11-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191112_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_spotify_id', models.CharField(max_length=100)),
                ('exc_spotify_id', models.CharField(max_length=100)),
                ('str_spotify_id', models.CharField(max_length=100)),
                ('rel_spotify_id', models.CharField(max_length=100)),
                ('int_spotify_id', models.CharField(max_length=100)),
                ('foc_spotify_id', models.CharField(max_length=100)),
                ('eng_playlist', models.CharField(max_length=100)),
                ('exc_playlist', models.CharField(max_length=100)),
                ('str_playlist', models.CharField(max_length=100)),
                ('rel_playlist', models.CharField(max_length=100)),
                ('int_playlist', models.CharField(max_length=100)),
                ('foc_playlist', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
